version: '2'
services:
  postgres:
    image: postgres:12-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - 'polymesh_postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: postgres

  fast-forward-alice:
    ports:
      - '30333:30333'
    build:
      context: .
      dockerfile: mesh.Dockerfile
    restart: "no"
    volumes:
      - 'polymesh_alice:/var/lib/polymesh/chains'
      - './faketime:/faketime'
    command:
      [
        '-d',
        '/var/lib/polymesh',
        '--chain=${CHAIN}',
        '--alice',
        '--validator',
        '--force-authoring',
      ]
  fast-forward-bob:
    ports:
      - '40333:30333'
    build:
      context: .
      dockerfile: mesh.Dockerfile
    restart: "no"
    volumes:
      - 'polymesh_bob:/var/lib/polymesh/chains'
      - './faketime:/faketime'
    command:
      [
        '-d',
        '/var/lib/polymesh',
        '--chain=${CHAIN}',
        '--bob',
        '--validator',
        '--force-authoring',
      ]
  fast-forward-charlie:
    ports:
      - '50333:30333'
    build:
      context: .
      dockerfile: mesh.Dockerfile
    restart: "no"
    volumes:
      - 'polymesh_charlie:/var/lib/polymesh/chains'
      - './faketime:/faketime'
    command:
      [
        '-d',
        '/var/lib/polymesh',
        '--chain=${CHAIN}',
        '--charlie',
        '--validator',
        '--force-authoring',
      ]

  alice:
    image: "polymathnet/polymesh:${POLYMESH_VERSION}-debian"
    user: root
    restart: always
    ports:
      - '9944:9944'
      - '9933:9933'
      - '40333:30333'
    volumes:
      - 'polymesh_alice:/var/lib/polymesh/chains'
    command:
      [
        '-d',
        '/var/lib/polymesh',
        '--chain=${CHAIN}',
        '--alice',
        '--validator',
        '--unsafe-rpc-external',
        '--unsafe-ws-external',
        '--rpc-cors=all',
        '--force-authoring',
      ]

  bob:
    image: "polymathnet/polymesh:${POLYMESH_VERSION}-debian"
    user: root
    restart: always
    ports:
      - '8833:9933'
      - '8844:9944'
      - '30333:30333'
    volumes:
      - 'polymesh_bob:/var/lib/polymesh/chains'
    command:
      [
        '-d',
        '/var/lib/polymesh',
        '--chain=${CHAIN}',
        '--bob',
        '--validator',
        '--unsafe-rpc-external',
        '--unsafe-ws-external',
        '--rpc-cors=all',
        '--force-authoring',
      ]

  charlie:
    image: "polymathnet/polymesh:${POLYMESH_VERSION}-debian"
    user: root
    restart: always
    ports:
      - '7733:9933'
      - '7744:9944'
      - '50333:30333'
    volumes:
      - 'polymesh_charlie:/var/lib/polymesh/chains'
    command:
      [
        '-d',
        '/var/lib/polymesh',
        '--chain=${CHAIN}',
        '--charlie',
        '--validator',
        '--unsafe-rpc-external',
        '--unsafe-ws-external',
        '--rpc-cors=all',
        '--force-authoring',
      ]

  subquery:
    image: 'polymathnet/polymesh-subquery:latest'
    restart: always
    depends_on:
      - 'postgres'
    ports:
      - 3006:3000
    environment:
      NETWORK_ENDPOINT: ws://alice:9944
      DB_USER: '${PG_USER}'
      DB_PASS: '${PG_PASSWORD}'
      DB_DATABASE: '${PG_DB}'
      DB_PORT: '${PG_PORT}'
      DB_HOST: '${PG_HOST}'
      NODE_ENV: local
    command:
      - --batch-size=500
      - -f=/app
      - --local

  tooling:
    image: polymathnet/tooling-gql:latest
    restart: always
    depends_on:
      - 'postgres'
    ports:
      - 3007:3000
    environment:
      PG_HOST: '${PG_HOST}'
      PG_USERNAME: '${PG_USER}'
      PG_PASSWORD: '${PG_PASSWORD}'
      STAGE: dev

  rest_api:
    image: polymathnet/polymesh-rest-api:latest
    restart: always
    ports:
      - 3004:3000
    environment:
      POLYMESH_NODE_URL: 'ws://alice:9944'
      POLYMESH_MIDDLEWARE_URL: 'http://tooling:3000'
      POLYMESH_MIDDLEWARE_API_KEY: '${TOOLING_API_KEY}'
      RELAYER_DIDS: '${RELAYER_DIDS}'
      RELAYER_MNEMONICS: '${RELAYER_MNEMONICS}'

  dashboard:
    image: nginx
    restart: always
    ports:
      - 3000:80
    volumes:
      - '${UI_DIR}/dashboard:/var/www/app:ro' # :ro -> read only
      - '${LOCAL_DIR}/nginx.conf:/etc/nginx/nginx.conf:ro'

  bridge:
    image: nginx
    restart: always
    ports:
      - 3001:80
    volumes:
      - '${UI_DIR}/bridge:/var/www/app:ro'
      - '${LOCAL_DIR}/nginx.conf:/etc/nginx/nginx.conf:ro'

  governance:
    image: nginx
    restart: always
    ports:
      - 3002:80
    volumes:
      - '${UI_DIR}/governance:/var/www/app:ro'
      - '${LOCAL_DIR}/nginx.conf:/etc/nginx/nginx.conf:ro'

  issuer:
    image: nginx
    restart: always
    ports:
      - 3003:80
    volumes:
      - '${UI_DIR}/issuer:/var/www/app:ro'
      - '${LOCAL_DIR}/nginx.conf:/etc/nginx/nginx.conf:ro'

  schema:
    image: nginx
    restart: always
    ports:
      - 3008:80
    volumes:
      - '${LOCAL_DIR}/schemas/polymesh_schema_${POLYMESH_VERSION}.json:/var/www/app/polymesh_schema.json:ro'
      - '${LOCAL_DIR}/nginx.conf:/etc/nginx/nginx.conf:ro'

volumes:
  polymesh_alice:
    external: true
  polymesh_bob:
    external: true
  polymesh_charlie:
    external: true
  polymesh_postgres:
    external: true

networks:
  default:
    name: 'polymesh-local'
