version: '2'
services:
  polymesh-node:
    image: 'polymathnet/polymesh:${POLYMESH_VERSION}-debian'
    network_mode: bridge
    ports:
      - '9933:9933'
      - '9944:9944'
      - '30333:30333'
    volumes:
      - '${DB_PATH}:/var/lib/polymesh/chains'
    command:
      [
        '-d',
        '/var/lib/polymesh',
        '--chain=testnet-dev',
        '--alice',
        '--validator',
        '--unsafe-rpc-external',
        '--unsafe-ws-external',
        '--rpc-cors=all',
        '--force-authoring',
      ]
