name: CI

on:
  push:
    branches: [master, beta, alpha]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          cache: 'yarn'
      - name: install dependencies
        run: yarn --frozen-lockfile
      - name: lint
        run: yarn lint

  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: install dependencies
        run: yarn --frozen-lockfile
      - name: test
        run: yarn test

  release:
    name: Building and releasing project
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          cache: 'yarn'
      - name: install dependencies
        run: yarn --frozen-lockfile
      - name: build
        run: |
          yarn build:ts
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.ASSOCIATION_NPM_TOKEN }}
        run: |
          yarn semantic-release
